---
name: Feature push

on:
  push:
    branches: [ 'features/**' ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    environment:
      name: validate

    env:
      TF_LOG: INFO

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Initialization
        id: init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
...